name: ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get versions
        id: versions
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=commit;]$(echo ${GITHUB_SHA:0:10})"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          load: true
          tags: tf-caprover-${{ steps.versions.outputs.branch }}-${{ steps.versions.outputs.commit }}:latest

      - 
        name: Docker Export 
        run: |
          docker save tf-caprover-${{ steps.versions.outputs.branch }}-${{ steps.versions.outputs.commit }}:latest | gzip > tf-caprover-${{ steps.versions.outputs.branch }}-${{ steps.versions.outputs.commit }}.tar.gz
      -
        name: Flist Upload
        run: |
          curl -H "Authorization: bearer ${{ secrets.HUB_TOKEN }}" -F file=@tf-caprover-${{ steps.versions.outputs.branch }}-${{ steps.versions.outputs.commit }}.tar.gz https://hub.grid.tf/api/flist/me/upload
